### ISSUE TITLE
Showing BtnCmd on portable device

### ISSUE THREAD

**Issue by Mrdindon** [MintyTrebor/BtnCmd#1]
Not sure if this is really an issue or just me not knowing how to do that but I would like to know if it is possible to see BtnCmd tab when accessing the printer from a portable device such as an Iphone ?

**Comment by jaysuk** [comment]
it displays ok for me.
are you clicking the 3 lines top left and then selecting btncmd from the panel that appears?

**Comment by MintyTrebor** [comment]
It does work on mobile (although I have only tested it on android chrome & firefox). A couple of things to note:
1. Not all DWC settings transfer between browsers. You may have to enable the plugin again on your mobile.
2. BtnCmd layouts do not transfer between browsers. Use the backup and restore features to copy layouts between browsers.
3. BtnCmd layouts do not scale (due to many reasons) so some layouts may have to be re-done to fit the mobile screen.
4. Some BtnCmd features are not available or limited on mobile - like alert monitoring.

**Comment by Mrdindon** [comment]
Ahhhh My bad, I didn't know I had to start the plugin from my mobile device as well
Thanks for the fast response !!!
That pluggin is crazy :) How can I buy you a beer ? :)

**Comment by MintyTrebor** [comment]
You're welcome, I'm glad you like it.
Thank you for the offer, but I only built it for fun/learning. 
The inspiration and a large dose of support came from [TeamGloomy](https://discord.com/invite/AG8Vgbqfkr) discord.
